{
  "uid" : "bc9f71c7da130729",
  "name" : "test_registration_negative[new email and empty email-Auto Test-1993--password-password-error_message5]",
  "fullName" : "tests.registration_page_test.TestRegistrationPage#test_registration_negative",
  "historyId" : "1e125368627084291d13088e40cc693c",
  "time" : {
    "start" : 1728608239031,
    "stop" : 1728608239031,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55606da8802a <unknown>\n#1 0x55606d76e5e0 <unknown>\n#2 0x55606d7667eb <unknown>\n#3 0x55606d756a09 <unknown>\n#4 0x55606d758744 <unknown>\n#5 0x55606d756cbd <unknown>\n#6 0x55606d75652f <unknown>\n#7 0x55606d756422 <unknown>\n#8 0x55606d754493 <unknown>\n#9 0x55606d754ada <unknown>\n#10 0x55606d770f41 <unknown>\n#11 0x55606d8028c5 <unknown>\n#12 0x55606d7e2b22 <unknown>\n#13 0x55606d801d7d <unknown>\n#14 0x55606d7e28c3 <unknown>\n#15 0x55606d7b06b3 <unknown>\n#16 0x55606d7b168e <unknown>\n#17 0x55606da52a2b <unknown>\n#18 0x55606da569b1 <unknown>\n#19 0x55606da3f225 <unknown>\n#20 0x55606da57532 <unknown>\n#21 0x55606da2438f <unknown>\n#22 0x55606da76f28 <unknown>\n#23 0x55606da770f3 <unknown>\n#24 0x55606da86e7c <unknown>\n#25 0x7efd67694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f84641cd51165f700e6231249b630d9f\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb25e21e690>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55606da770f3 \\\\u003Cunknown>\\\\n#24 0x55606da86e7c \\\\u003Cunknown>\\\\n#25 0x7efd67694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55606da8802a <unknown>\nE       #1 0x55606d76e5e0 <unknown>\nE       #2 0x55606d7667eb <unknown>\nE       #3 0x55606d756a09 <unknown>\nE       #4 0x55606d758744 <unknown>\nE       #5 0x55606d756cbd <unknown>\nE       #6 0x55606d75652f <unknown>\nE       #7 0x55606d756422 <unknown>\nE       #8 0x55606d754493 <unknown>\nE       #9 0x55606d754ada <unknown>\nE       #10 0x55606d770f41 <unknown>\nE       #11 0x55606d8028c5 <unknown>\nE       #12 0x55606d7e2b22 <unknown>\nE       #13 0x55606d801d7d <unknown>\nE       #14 0x55606d7e28c3 <unknown>\nE       #15 0x55606d7b06b3 <unknown>\nE       #16 0x55606d7b168e <unknown>\nE       #17 0x55606da52a2b <unknown>\nE       #18 0x55606da569b1 <unknown>\nE       #19 0x55606da3f225 <unknown>\nE       #20 0x55606da57532 <unknown>\nE       #21 0x55606da2438f <unknown>\nE       #22 0x55606da76f28 <unknown>\nE       #23 0x55606da770f3 <unknown>\nE       #24 0x55606da86e7c <unknown>\nE       #25 0x7efd67694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728608239031,
      "stop" : 1728608239795,
      "duration" : 764
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728608130626,
      "stop" : 1728608130626,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728608239795,
      "stop" : 1728608240275,
      "duration" : 480
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55606da8802a <unknown>\n#1 0x55606d76e5e0 <unknown>\n#2 0x55606d7667eb <unknown>\n#3 0x55606d756a09 <unknown>\n#4 0x55606d758744 <unknown>\n#5 0x55606d756cbd <unknown>\n#6 0x55606d75652f <unknown>\n#7 0x55606d756422 <unknown>\n#8 0x55606d754493 <unknown>\n#9 0x55606d754ada <unknown>\n#10 0x55606d770f41 <unknown>\n#11 0x55606d8028c5 <unknown>\n#12 0x55606d7e2b22 <unknown>\n#13 0x55606d801d7d <unknown>\n#14 0x55606d7e28c3 <unknown>\n#15 0x55606d7b06b3 <unknown>\n#16 0x55606d7b168e <unknown>\n#17 0x55606da52a2b <unknown>\n#18 0x55606da569b1 <unknown>\n#19 0x55606da3f225 <unknown>\n#20 0x55606da57532 <unknown>\n#21 0x55606da2438f <unknown>\n#22 0x55606da76f28 <unknown>\n#23 0x55606da770f3 <unknown>\n#24 0x55606da86e7c <unknown>\n#25 0x7efd67694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728608239795,
        "stop" : 1728608240274,
        "duration" : 479
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55606da8802a <unknown>\n#1 0x55606d76e5e0 <unknown>\n#2 0x55606d7667eb <unknown>\n#3 0x55606d756a09 <unknown>\n#4 0x55606d758744 <unknown>\n#5 0x55606d756cbd <unknown>\n#6 0x55606d75652f <unknown>\n#7 0x55606d756422 <unknown>\n#8 0x55606d754493 <unknown>\n#9 0x55606d754ada <unknown>\n#10 0x55606d770f41 <unknown>\n#11 0x55606d8028c5 <unknown>\n#12 0x55606d7e2b22 <unknown>\n#13 0x55606d801d7d <unknown>\n#14 0x55606d7e28c3 <unknown>\n#15 0x55606d7b06b3 <unknown>\n#16 0x55606d7b168e <unknown>\n#17 0x55606da52a2b <unknown>\n#18 0x55606da569b1 <unknown>\n#19 0x55606da3f225 <unknown>\n#20 0x55606da57532 <unknown>\n#21 0x55606da2438f <unknown>\n#22 0x55606da76f28 <unknown>\n#23 0x55606da770f3 <unknown>\n#24 0x55606da86e7c <unknown>\n#25 0x7efd67694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"f84641cd51165f700e6231249b630d9f\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728608240328,
      "stop" : 1728608240390,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Registration Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "registration_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationPage"
  }, {
    "name" : "host",
    "value" : "fv-az523-260"
  }, {
    "name" : "thread",
    "value" : "2358-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.registration_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "birthday",
    "value" : "1993"
  }, {
    "name" : "confirm_password",
    "value" : "'password'"
  }, {
    "name" : "email",
    "value" : "''"
  }, {
    "name" : "error_message",
    "value" : "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']"
  }, {
    "name" : "first_name",
    "value" : "'Auto Test'"
  }, {
    "name" : "password",
    "value" : "'password'"
  }, {
    "name" : "title",
    "value" : "'new email and empty email'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 6,
        "unknown" : 0,
        "total" : 7
      },
      "items" : [ {
        "uid" : "743f2b7d02d8051f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/288//#testresult/743f2b7d02d8051f",
        "status" : "passed",
        "time" : {
          "start" : 1727170988962,
          "stop" : 1727170989599,
          "duration" : 637
        }
      }, {
        "uid" : "b5ecc6b911953a99",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/118//#testresult/b5ecc6b911953a99",
        "status" : "passed",
        "time" : {
          "start" : 1725929999860,
          "stop" : 1725930000518,
          "duration" : 658
        }
      }, {
        "uid" : "bc4bf06b61988af0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/211//#testresult/bc4bf06b61988af0",
        "status" : "passed",
        "time" : {
          "start" : 1724228485443,
          "stop" : 1724228486053,
          "duration" : 610
        }
      }, {
        "uid" : "c2a16654cdb22033",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/194//#testresult/c2a16654cdb22033",
        "status" : "passed",
        "time" : {
          "start" : 1723447717029,
          "stop" : 1723447717623,
          "duration" : 594
        }
      }, {
        "uid" : "90223bc2e379ebde",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/171//#testresult/90223bc2e379ebde",
        "status" : "passed",
        "time" : {
          "start" : 1722669611526,
          "stop" : 1722669612115,
          "duration" : 589
        }
      }, {
        "uid" : "7f7bdad6cdb6b8f8",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/63//#testresult/7f7bdad6cdb6b8f8",
        "status" : "passed",
        "time" : {
          "start" : 1721177879462,
          "stop" : 1721177880087,
          "duration" : 625
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "bc9f71c7da130729.json",
  "parameterValues" : [ "1993", "'password'", "''", "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']", "'Auto Test'", "'password'", "'new email and empty email'" ]
}